version: "3.4"
services:
  mosquitto:
    image: eclipse-mosquitto
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    entrypoint:
      - mosquitto
    networks:
      mqtt_net:
        ipv4_address: 172.19.0.11

  paho:
    build: paho
    container_name: paho
    command: /usr/sbin/sshd -D
    ports:
      - "49944:22"
    volumes:
      - type: bind
        source: ./work
        target: /work
    networks:
      mqtt_net:
        ipv4_address: 172.19.0.12

networks:
  mqtt_net:
    ipam:
      config:
        - subnet: 172.19.0.0/16
